[platformio]
default_envs = esp32-s3-devkitc-1

[env:esp32-s3-devkitc-1]
platform = espressif32
; 必须用S3专用板型
board = esp32-s3-devkitc-1
framework = arduino

upload_port = COM8
monitor_port = COM8
monitor_speed = 115200

; --------------------------
; N16R8 专属关键配置
; --------------------------
; 1. Flash 配置 (16MB QIO)
board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216
board_build.flash_mode = qio
; 使用16MB分区表
board_build.partitions = default_16MB.csv

; 2. PSRAM 配置 (8MB OPI)
board_build.psram_enable = true
board_build.psram_type = opi
; 启用PSRAM宏
build_flags =
  -DBOARD_HAS_PSRAM
  -DLV_CONF_INCLUDE_SIMPLE
  -DLV_USE_DRAW_SWP=1
  -I./src

lib_deps =
  lvgl/lvgl@^9.5.0