[platformio]
default_envs = esp32s3

[env:esp32s3]
platform = espressif32@6.9.0
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
monitor_filters = 
	time
	debug
upload_speed = 115200
upload_port = COM9
board_build.flash_mode = qio
build_flags = 
	-Os
	-DLV_CONF_INCLUDE_SIMPLE
	-DCONFIG_ESP_WIFI_IRAM_OPT=0
	-DCONFIG_ESP_WIFI_RX_IRAM_OPT=0
	-DCONFIG_ESP_WIFI_EXTRA_IRAM_OPT=0
	-Iinclude
lib_extra_dirs = lib
lib_deps =
	fbiego/CST816S
	lvgl/lvgl@^8.4.0
	bblanchon/ArduinoJson @ ^7.0.0
