[platformio]
default_envs = esp32s3

[env:esp32s3]
platform = espressif32@6.9.0
board = esp32-s3-devkitc-1
framework = arduino

monitor_speed = 115200
monitor_filters = color, time, debug
upload_speed = 921600
upload_port = auto

board_build.partitions = default_16MB.csv
board_build.flash_mode = qio
board_build.f_cpu = 240000000L
board_build.arduino.memory_type = qio_opi
board_build.psram_mode = opi
board_build.psram_freq = 80m

build_flags =
  -DARDUINO_USB_CDC_ON_BOOT=1
  -DBOARD_HAS_PSRAM
  -DCORE_DEBUG_LEVEL=5
  -Og
  -DDEBUG_ESP_PORT=Serial
  -DLV_CONF_INCLUDE_SIMPLE

lib_deps =
  lovyan03/LovyanGFX@^1.1.16
  fbiego/CST816S
  lewisxhe/SensorLib@^0.4.0
  https://github.com/pschatzmann/arduino-audio-driver.git
  lvgl/lvgl@^8.4.0