"""
Minimal demo: Random Forest → C array for ESP32-S3 activity recognition.

Usage:
    # 1. Collect data (walk = press 1, run = press 2, idle = press 4)
    python collect_data.py COM9

    # 2. Train + export C code
    python train_rf.py imu_data_20260521_*.csv

    # 3. Copy the printed C arrays into src/activity.h, then rebuild firmware.
"""
import os
os.environ['KMP_DUPLICATE_LIB_OK'] = 'TRUE'

import sys
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from collections import Counter

LABEL_NAMES = {1: 'walk', 2: 'run', 4: 'idle', 9: 'bike', 10: 'stairs'}
WINDOW = 50       # 1 second @ 50Hz
STRIDE = 25       # 50% overlap


def load_csv(path):
    """Load CSV, return (data, labels)."""
    raw = np.loadtxt(path, delimiter=',', skiprows=1,
                     usecols=range(1, 8),  # ax,ay,az,gx,gy,gz,label
                     dtype=str, ndmin=2)
    if raw.ndim == 1:
        raw = raw.reshape(1, -1)
    data = raw[:, :6].astype(np.float32)
    label_vals = np.array([int(float(l)) for l in raw[:, 6]])
    valid = np.isin(label_vals, list(LABEL_NAMES.keys()))
    return data[valid], label_vals[valid]


def extract_features(window):
    """12 features: mean & std for each of 6 axes."""
    return np.concatenate([window.mean(axis=0), window.std(axis=0)])


def create_windows(data, labels):
    """Sliding window → feature vectors."""
    X, y = [], []
    for start in range(0, len(data) - WINDOW + 1, STRIDE):
        X.append(extract_features(data[start:start + WINDOW]))
        win_labels = labels[start:start + WINDOW]
        y.append(Counter(win_labels).most_common(1)[0][0])
    return np.array(X), np.array(y)


def export_c_code(model, feature_names, class_names):
    """Print C code for Random Forest inference."""
    n_classes = len(class_names)
    print(f"// Auto-generated by train_rf.py — {len(model.estimators_)} trees")
    print(f"// Features: {feature_names}")
    print(f"// Classes: {class_names}")
    print()

    # Collect all tree structures
    print("// Tree nodes: { feat_idx, threshold, left_child, right_child, leaf_class }")
    print("typedef struct { int f; float t; int l; int r; int cls; } RFNode;")
    print()

    for ti, tree in enumerate(model.estimators_):
        t = tree.tree_
        n_nodes = t.node_count
        left = t.children_left
        right = t.children_right
        feat = t.feature
        thresh = t.threshold
        value = t.value

        print(f"// Tree {ti} — {n_nodes} nodes")
        print(f"static const RFNode tree_{ti}[{n_nodes}] = {{")
        for i in range(n_nodes):
            if left[i] == -1:  # leaf
                cls = int(np.argmax(value[i][0]))
                print(f"  {{-1, 0, -1, -1, {cls}}},")
            else:
                print(f"  {{{feat[i]}, {thresh[i]:.4f}f, {left[i]}, {right[i]}, -1}},")
        print("};")
        print()

    # Inference function
    print("// Predict: returns class index, -1 if no tree votes")
    print(f"static int rf_predict(const float features[12]) {{")
    print(f"  int votes[{n_classes}] = {{0}};")
    print(f"  int n_trees = {len(model.estimators_)};")
    print("  const RFNode* trees[] = {")
    for ti in range(len(model.estimators_)):
        end = "," if ti < len(model.estimators_) - 1 else " "
        print(f"    tree_{ti}{end}")
    print("  };")
    print("  const int tree_sizes[] = {")
    for ti, tree in enumerate(model.estimators_):
        end = "," if ti < len(model.estimators_) - 1 else " "
        print(f"    {tree.tree_.node_count}{end}")
    print("  };")
    print()
    print("  for (int t = 0; t < n_trees; t++) {")
    print("    int n = 0;")
    print("    while (1) {")
    print("      if (trees[t][n].f < 0) {  // leaf")
    print("        votes[trees[t][n].cls]++;")
    print("        break;")
    print("      }")
    print("      if (features[trees[t][n].f] <= trees[t][n].t)")
    print("        n = trees[t][n].l;")
    print("      else")
    print("        n = trees[t][n].r;")
    print("    }")
    print("  }")
    print()
    print("  int best = 0;")
    print(f"  for (int c = 1; c < {n_classes}; c++)")
    print("    if (votes[c] > votes[best]) best = c;")
    print("  return best;")
    print("}")


def main():
    if len(sys.argv) < 2:
        print("Usage: python train_rf.py <csv_file>")
        sys.exit(1)

    data, labels = load_csv(sys.argv[1])
    print(f"Loaded {len(data)} frames, {len(set(labels))} classes")

    X, y = create_windows(data, labels)
    print(f"Windows: {len(X)}, features per window: {X.shape[1]}")
    print(f"Classes: {dict(zip(*np.unique(y, return_counts=True)))}")

    model = RandomForestClassifier(n_estimators=10, max_depth=4,
                                   random_state=42, n_jobs=-1)
    model.fit(X, y)
    acc = model.score(X, y)
    print(f"Train accuracy: {acc:.3f}")

    # Cross-val estimate
    from sklearn.model_selection import cross_val_score
    cv = cross_val_score(model, X, y, cv=3)
    print(f"Cross-val accuracy: {cv.mean():.3f} +/- {cv.std():.3f}")

    feature_names = ['mean_ax', 'mean_ay', 'mean_az',
                     'mean_gx', 'mean_gy', 'mean_gz',
                     'std_ax', 'std_ay', 'std_az',
                     'std_gx', 'std_gy', 'std_gz']
    # Build class names dynamically from present labels
    present_labels = sorted(set(y))
    class_names = [LABEL_NAMES.get(l, f'class_{l}') for l in present_labels]

    export_c_code(model, feature_names, class_names)


if __name__ == '__main__':
    main()
